export const KEY_TOKEN = 'token'
export const KEY_ID = 'hdc2024ManagerId'
export const KEY_ROLE = 'keyRole'
export const KEY_STORE_ID = 'keyStoreId'
export const KEY_CITY = 'keyCityManageId'
export const KEY_REGION = 'keyRegionManageId'
export const KEY_AUTH_USER = 'hdcAdminUser'
