server:
  port: 8088
  servlet:
    context-path: /hdc/api

spring:
  application:
    name: hdc-factory-mqtt-demo
  sql:
    init:
      mode: never
  task:
    scheduling:
      enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/hdc?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-timeout: 1000
      initialization-fail-timeout: -1

mqtt:
  enabled: true
  url: tcp://192.168.1.200
  port: 1883
factory:
  runtime:
    mqtt-timeout-seconds: 30
    buffer-capacity: 6
  mqtt:
    enabled: true
  enterprise:
    plc:
      enabled: true
      switch-devices: PK-ARM-01,FIL-HEAD-01,PT-CV-01,AGV-01
    dobot:
      enabled: false
      host: 192.168.1.6
      port: 29999
      packing-script: blockly_hdc2024
  persistence:
    enabled: false
  thresholds:
    voc-max: 10.0
    smoke-max: 0.5
    temperature-min: 20.0
    temperature-max: 30.0
    agv-distance-min: 20.0

file:
  path: D:\HarmonyOS-Dev\Runtime\hdc\files\hdc
  url: http://localhost:8088/files/hdc/
