server:
  port: 8088
  servlet:
    context-path: /hdc/api

spring:
  application:
    name: hdc-factory-demo
  sql:
    init:
      mode: always
  task:
    scheduling:
      enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/hdc?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-timeout: 1000
      initialization-fail-timeout: -1

mqtt:
  enabled: false
  url: tcp://127.0.0.1
  port: 31883
factory:
  runtime:
    mqtt-timeout-seconds: 5
    buffer-capacity: 6
  mqtt:
    enabled: false
  persistence:
    enabled: true
  thresholds:
    voc-max: 10.0
    smoke-max: 0.5
    temperature-min: 20.0
    temperature-max: 30.0
    agv-distance-min: 20.0

file:
  path: E:\hdc_runtime\files\hdc
  url: http://localhost:8088/files/hdc/
