<template>
	<div class="users-page"><header class="page-title"><div><span>ACCESS CONTROL</span><h1>用户与权限</h1><p>管理后台账号角色和启用状态。新注册账号默认为只读用户。</p></div><el-button icon="el-icon-refresh" @click="load">刷新</el-button></header><section class="role-guide"><div><b>系统管理员</b><span>用户管理、产线控制、报警处理和全部查看权限</span></div><div><b>产线操作员</b><span>产线控制、报警处理和全部查看权限</span></div><div><b>只读用户</b><span>仅查看后台数据，不能执行任何写操作</span></div></section><section class="table-panel"><el-table :data="users" stripe v-loading="loading"><el-table-column prop="username" label="用户名" min-width="130"></el-table-column><el-table-column prop="displayName" label="姓名" min-width="130"></el-table-column><el-table-column label="角色" width="160"><template slot-scope="scope"><el-select v-model="scope.row.role" :disabled="saving===scope.row.id"><el-option label="系统管理员" value="ADMIN"></el-option><el-option label="产线操作员" value="OPERATOR"></el-option><el-option label="只读用户" value="VIEWER"></el-option></el-select></template></el-table-column><el-table-column label="状态" width="120"><template slot-scope="scope"><el-switch v-model="scope.row.status" active-value="ACTIVE" inactive-value="DISABLED" active-color="#4da86a" inactive-color="#b7bec0"></el-switch><span class="status-label">{{ scope.row.status==='ACTIVE'?'启用':'停用' }}</span></template></el-table-column><el-table-column label="最后登录" min-width="170"><template slot-scope="scope">{{ formatTime(scope.row.lastLoginAt) }}</template></el-table-column><el-table-column label="创建时间" min-width="170"><template slot-scope="scope">{{ formatTime(scope.row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template slot-scope="scope"><el-button type="primary" plain :loading="saving===scope.row.id" @click="save(scope.row)">保存</el-button></template></el-table-column></el-table></section></div>
</template>
<script>
import { getUsers, updateUser } from '@/api/AuthService.js'
export default { data(){return{loading:false,saving:null,users:[]}},mounted(){this.load()},methods:{async load(){this.loading=true;try{this.users=await getUsers()||[]}finally{this.loading=false}},async save(user){this.saving=user.id;try{await updateUser(user.id,{role:user.role,status:user.status});this.$message.success('用户权限已更新');await this.load()}catch(error){await this.load()}finally{this.saving=null}},formatTime(value){if(!value)return'从未登录';return String(value).replace('T',' ').slice(0,19)}}}
</script>
<style scoped>
.users-page{min-height:100%;padding:24px;background:#edf0f1}.page-title{display:flex;justify-content:space-between;align-items:flex-end;gap:16px}.page-title span{color:#8c6917;font:700 9px Consolas,monospace}.page-title h1{margin:6px 0 4px;font-size:26px}.page-title p{margin:0;color:#778287;font-size:11px}.page-title .el-button{border-radius:2px}.role-guide{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:17px 0}.role-guide>div{padding:13px;border:1px solid #c3cacc;border-left:3px solid #d19a22;background:#fafafa}.role-guide b,.role-guide span{display:block}.role-guide b{font-size:11px}.role-guide span{margin-top:5px;color:#7d888c;font-size:9px;line-height:1.5}.table-panel{padding:15px;border:1px solid #c3cacc;background:#fafafa}.status-label{margin-left:7px;color:#687378;font-size:9px}.el-select{width:130px}.el-button{border-radius:2px}@media(max-width:700px){.users-page{padding:16px 12px}.page-title{align-items:flex-start;flex-direction:column}.role-guide{grid-template-columns:1fr}}
</style>
