<template>
	<div class="admin-layout" :class="{ collapsed }">
		<aside class="sidebar" :class="{ mobileOpen }">
			<div class="sidebar-brand"><img src="../../assets/hdc_demo.png" alt="系统标志"><div><b>装瓶产线</b><span>运营管理后台</span></div></div>
			<el-menu :default-active="$route.path" :collapse="collapsed" router background-color="#172025" text-color="#aeb8bc" active-text-color="#f0b429">
				<el-menu-item index="/dashboard"><i class="el-icon-odometer"></i><span slot="title">运营首页</span></el-menu-item>
				<el-submenu index="production"><template slot="title"><i class="el-icon-s-operation"></i><span>生产运营</span></template><el-menu-item index="/factory">产线控制中心</el-menu-item><el-menu-item index="/incidents">异常处置中心</el-menu-item></el-submenu>
				<el-submenu index="devices"><template slot="title"><i class="el-icon-cpu"></i><span>设备管理</span></template><el-menu-item index="/plc-control">PLC 实验台</el-menu-item><el-menu-item index="/plc-cabinet">PLC 控制柜</el-menu-item></el-submenu>
				<el-submenu index="warehouse"><template slot="title"><i class="el-icon-box"></i><span>物料仓储</span></template><el-menu-item index="/products">物料与产品</el-menu-item><el-menu-item index="/warehouse-records">扫码记录</el-menu-item></el-submenu>
				<el-menu-item index="/reports"><i class="el-icon-document"></i><span slot="title">生产报表</span></el-menu-item>
				<el-submenu index="system"><template slot="title"><i class="el-icon-setting"></i><span>系统管理</span></template><el-menu-item v-if="auth.isAdmin" index="/users">用户与权限</el-menu-item><el-menu-item index="/setting">系统配置</el-menu-item></el-submenu>
			</el-menu>
			<div class="sidebar-foot"><i></i><span v-if="!collapsed">服务运行中</span></div>
		</aside>
		<div v-if="mobileOpen" class="mobile-mask" @click="mobileOpen=false"></div>
		<section class="admin-main">
			<header class="topbar"><div class="topbar-left"><button type="button" class="menu-button" @click="toggleSidebar"><i :class="collapsed ? 'el-icon-s-unfold' : 'el-icon-s-fold'"></i></button><div class="breadcrumb"><span>{{ $route.meta.group || '管理后台' }}</span><b>/</b><strong>{{ $route.meta.title }}</strong></div></div><div class="topbar-actions"><button type="button" class="screen-link" @click="openScreen"><i class="el-icon-monitor"></i><span>打开数字大屏</span></button><div class="backend-state"><i></i>后端在线</div><el-dropdown trigger="click" @command="handleCommand"><button class="user-button" type="button"><span class="avatar">{{ userInitial }}</span><span class="user-copy"><b>{{ user.displayName }}</b><small>{{ roleLabel(user.role) }}</small></span><i class="el-icon-arrow-down"></i></button><el-dropdown-menu slot="dropdown"><el-dropdown-item command="users" v-if="auth.isAdmin" icon="el-icon-user">用户与权限</el-dropdown-item><el-dropdown-item command="logout" divided icon="el-icon-switch-button">退出登录</el-dropdown-item></el-dropdown-menu></el-dropdown></div></header>
			<main class="page-content"><router-view /></main>
		</section>
	</div>
</template>
<script>
import auth from '@/store/auth.js'
export default { data() { return { auth, collapsed: false, mobileOpen: false } }, computed: { user() { return auth.state.user || { displayName: '用户', role: 'VIEWER' } }, userInitial() { return (this.user.displayName || this.user.username || 'U').slice(0, 1) } }, methods: { toggleSidebar() { if (window.innerWidth <= 760) this.mobileOpen = !this.mobileOpen; else this.collapsed = !this.collapsed }, openScreen() { window.open('http://localhost:8081/#/factoryOverview', '_blank') }, roleLabel(role) { return { ADMIN: '系统管理员', OPERATOR: '产线操作员', VIEWER: '只读用户' }[role] || role }, async handleCommand(command) { if (command === 'users') return this.$router.push('/users'); if (command === 'logout') { await auth.signOut(); this.$router.replace('/login') } } }, watch: { '$route.path'() { this.mobileOpen = false } } }
</script>
<style scoped>
.admin-layout { display: flex; width: 100%; height: 100%; color: #263136; background: #edf0f1; }.sidebar { position: relative; z-index: 20; display: flex; flex-direction: column; flex: 0 0 226px; width: 226px; background: #172025; transition: width .18s ease, flex-basis .18s ease; }.collapsed .sidebar { flex-basis: 64px; width: 64px; }.sidebar-brand { display: flex; align-items: center; gap: 10px; height: 64px; padding: 0 16px; overflow: hidden; border-bottom: 1px solid #3d484d; white-space: nowrap; }.sidebar-brand img { flex: 0 0 auto; width: 31px; height: 31px; object-fit: contain; }.sidebar-brand b, .sidebar-brand span { display: block; }.sidebar-brand b { color: #edf0f1; font-size: 14px; }.sidebar-brand span { margin-top: 3px; color: #748187; font-size: 9px; }.sidebar .el-menu { flex: 1; overflow-y: auto; border-right: 0; }.sidebar :deep(.el-menu-item), .sidebar :deep(.el-submenu__title) { height: 48px; line-height: 48px; }.sidebar :deep(.el-menu-item.is-active) { border-left: 3px solid #e9aa24; background: #202b30 !important; }.sidebar :deep(.el-submenu .el-menu-item) { min-width: 0; background: #11181b !important; }.sidebar-foot { display: flex; align-items: center; gap: 8px; min-height: 45px; padding: 0 20px; color: #819096; border-top: 1px solid #3d484d; font-size: 9px; white-space: nowrap; }.sidebar-foot i, .backend-state i { width: 7px; height: 7px; border-radius: 50%; background: #53b875; }.admin-main { display: flex; flex: 1; min-width: 0; flex-direction: column; }.topbar { display: flex; justify-content: space-between; align-items: center; flex: 0 0 64px; min-width: 0; padding: 0 20px; border-bottom: 1px solid #c8ced0; background: #f7f8f8; }.topbar-left, .topbar-actions, .user-button { display: flex; align-items: center; }.menu-button { width: 36px; height: 36px; margin-right: 12px; color: #394449; border: 0; background: transparent; cursor: pointer; font-size: 20px; }.breadcrumb { display: flex; align-items: center; gap: 8px; color: #828c90; font-size: 11px; }.breadcrumb b { color: #b7bec0; }.breadcrumb strong { color: #303b40; }.topbar-actions { gap: 15px; }.screen-link { display: flex; align-items: center; gap: 6px; height: 32px; padding: 0 10px; color: #59656a; border: 1px solid #b6bec1; border-radius: 2px; background: #fff; cursor: pointer; }.backend-state { display: flex; align-items: center; gap: 6px; color: #5b676c; font-size: 9px; }.user-button { gap: 8px; padding: 0; border: 0; background: transparent; cursor: pointer; }.avatar { display: grid; place-items: center; width: 31px; height: 31px; color: #1d2528; border-radius: 2px; background: #e9aa24; font-weight: bold; }.user-copy { text-align: left; }.user-copy b, .user-copy small { display: block; }.user-copy b { color: #303a3f; font-size: 11px; }.user-copy small { margin-top: 3px; color: #879195; font-size: 8px; }.page-content { flex: 1; min-height: 0; overflow: auto; }.mobile-mask { display: none; }
@media (max-width: 760px) { .sidebar, .collapsed .sidebar { position: fixed; top: 0; bottom: 0; left: -226px; width: 226px; transition: left .18s ease; }.sidebar.mobileOpen { left: 0; }.mobile-mask { position: fixed; z-index: 15; inset: 0; display: block; background: rgba(0,0,0,.45); }.breadcrumb span, .breadcrumb b, .backend-state, .screen-link span, .user-copy { display: none; }.topbar { padding: 0 10px; }.topbar-actions { gap: 9px; } }
</style>
