<template>
	<div class="register-page"><div class="register-panel"><button class="back" type="button" @click="$router.push('/login')">← 返回登录</button><div class="heading"><span>ACCOUNT APPLICATION</span><h1>注册只读账号</h1><p>新账号只能查看生产数据。设备控制权限需由管理员登录后分配。</p></div><el-alert title="安全规则" description="公开注册不会授予产线控制、报警确认或用户管理权限。" type="warning" :closable="false" show-icon></el-alert><el-form ref="form" :model="form" :rules="rules" label-position="top" @submit.native.prevent="submit"><el-form-item label="用户名" prop="username"><el-input v-model.trim="form.username" placeholder="3-32位字母、数字或下划线"></el-input></el-form-item><el-form-item label="姓名" prop="displayName"><el-input v-model.trim="form.displayName" placeholder="用于后台顶部和操作审计"></el-input></el-form-item><el-form-item label="密码" prop="password"><el-input v-model="form.password" type="password" show-password placeholder="至少8位"></el-input></el-form-item><el-form-item label="确认密码" prop="confirmPassword"><el-input v-model="form.confirmPassword" type="password" show-password></el-input></el-form-item><el-button type="primary" native-type="submit" :loading="loading">提交注册</el-button></el-form></div></div>
</template>
<script>
import { register } from '@/api/AuthService.js'
export default { data() { const confirm = (rule, value, callback) => value !== this.form.password ? callback(new Error('两次密码不一致')) : callback(); return { loading: false, form: { username: '', displayName: '', password: '', confirmPassword: '' }, rules: { username: [{ required: true, message: '请输入用户名', trigger: 'blur' }, { pattern: /^[A-Za-z0-9_]{3,32}$/, message: '格式不正确', trigger: 'blur' }], displayName: [{ required: true, message: '请输入姓名', trigger: 'blur' }], password: [{ required: true, min: 8, max: 72, message: '密码长度需为8-72位', trigger: 'blur' }], confirmPassword: [{ required: true, validator: confirm, trigger: 'blur' }] } } }, methods: { submit() { this.$refs.form.validate(async valid => { if (!valid || this.loading) return; this.loading = true; try { await register({ username: this.form.username, displayName: this.form.displayName, password: this.form.password }); this.$alert('账号已创建，当前角色为只读用户。请返回登录。', '注册成功', { confirmButtonText: '返回登录', callback: () => this.$router.replace('/login') }) } catch (error) { if (!error.response) this.$message.error(error.message || '注册失败') } finally { this.loading = false } }) } } }
</script>
<style scoped>
.register-page { display: grid; place-items: center; min-height: 100%; padding: 32px 18px; overflow: auto; color: #253035; background-color: #172025; background-image: linear-gradient(rgba(255,255,255,.035) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.035) 1px, transparent 1px); background-size: 32px 32px; }.register-panel { width: min(520px, 100%); padding: 28px 34px; border-top: 5px solid #e9aa24; border-radius: 2px; background: #eef0f1; }.back { padding: 0; color: #5d696e; border: 0; background: transparent; cursor: pointer; }.heading { margin: 24px 0 17px; }.heading span { color: #8a6715; font: bold 9px Consolas, monospace; }.heading h1 { margin: 7px 0; font-size: 27px; }.heading p { margin: 0; color: #6f7a7f; font-size: 11px; line-height: 1.6; }.el-alert { margin-bottom: 18px; border-radius: 2px; }.el-button { width: 100%; height: 42px; border-color: #b57f14; border-radius: 2px; background: #c78d19; }
</style>
